const adminPassword = () => sessionStorage.getItem('ssb-admin-password') || '';
const request = async (url, options = {}) => { const response = await fetch(url, { ...options, headers: { 'Content-Type': 'application/json', 'X-Admin-Password': adminPassword(), ...(options.headers || {}) } }); const body = await response.json(); if (!response.ok) throw new Error(body.detail || body.error || 'Request failed'); return body; };
const $ = (id) => document.getElementById(id); const loginPanel = $('login-panel'), dashboard = $('dashboard'), loginForm = $('login-form'), loginMessage = $('login-message'), accountForm = $('account-form'), accountMessage = $('account-message'), accountList = $('account-list'), accountSelect = $('video-account'), videoForm = $('video-form'), videoMessage = $('video-message'), videoList = $('video-list');
async function renderAccounts() { const accounts = await request('/api/admin/accounts'); accountSelect.innerHTML = '<option value="">Choose account</option>'; accountList.innerHTML = accounts.length ? '' : '<p class="empty">No Cloudinary account added yet.</p>'; accounts.forEach((account) => { accountSelect.add(new Option(account.name, account.id)); const row = document.createElement('div'); row.className = 'account-entry'; row.innerHTML = `<div><strong>${account.name}</strong><span>${account.cloudName}</span></div><button class="delete" type="button">Remove</button>`; row.querySelector('button').onclick = async () => { try { await request(`/api/admin/accounts/${account.id}`, { method: 'DELETE' }); renderAccounts(); } catch (error) { accountMessage.textContent = error.message; } }; accountList.append(row); }); }
async function renderVideos() { const items = await request('/api/admin/videos'); videoList.innerHTML = items.length ? '' : '<p class="empty">No lodge videos published yet.</p>'; items.forEach((item, index) => { const row = document.createElement('div'); row.className = 'video-entry'; row.innerHTML = `<div><strong>${String(index + 1).padStart(2, '0')} · ${item.title}</strong><span>${item.category || 'Lodge video'}</span></div><div class="video-actions"><button class="move" type="button" ${index === 0 ? 'disabled' : ''}>↑</button><button class="move" type="button" ${index === items.length - 1 ? 'disabled' : ''}>↓</button><button class="delete" type="button">Remove</button></div>`; const [up, down, remove] = row.querySelectorAll('button'); const order = async () => { await request('/api/admin/videos/order', { method: 'PUT', body: JSON.stringify({ ids: items.map((video) => video.id) }) }); renderVideos(); }; up.onclick = () => { [items[index - 1], items[index]] = [items[index], items[index - 1]]; order(); }; down.onclick = () => { [items[index], items[index + 1]] = [items[index + 1], items[index]]; order(); }; remove.onclick = async () => { await request(`/api/admin/videos/${item.id}`, { method: 'DELETE' }); renderVideos(); }; videoList.append(row); }); }
async function showDashboard() { loginPanel.hidden = true; dashboard.hidden = false; await Promise.all([renderAccounts(), renderVideos()]); }
loginForm.onsubmit = async (event) => { event.preventDefault(); sessionStorage.setItem('ssb-admin-password', $('password').value); try { await request('/api/admin/verify', { method: 'POST' }); showDashboard(); } catch (error) { sessionStorage.removeItem('ssb-admin-password'); loginMessage.textContent = error.message; } };
if (adminPassword()) request('/api/admin/verify', { method: 'POST' }).then(showDashboard).catch(() => sessionStorage.removeItem('ssb-admin-password'));
$('logout').onclick = () => { sessionStorage.removeItem('ssb-admin-password'); dashboard.hidden = true; loginPanel.hidden = false; loginForm.reset(); };
accountForm.onsubmit = async (event) => { event.preventDefault(); try { const account = await request('/api/admin/accounts', { method: 'POST', body: JSON.stringify({ name: $('account-name').value.trim(), cloud_name: $('cloud-name').value.trim(), api_key: $('api-key').value.trim(), api_secret: $('api-secret').value.trim() }) }); accountForm.reset(); accountMessage.textContent = `${account.name} is ready for upload.`; renderAccounts(); } catch (error) { accountMessage.textContent = error.message; } };
videoForm.onsubmit = async (event) => { event.preventDefault(); const file = $('video-file').files[0]; if (!file) return; try { videoMessage.textContent = 'Creating secure Cloudinary upload…'; const signed = await request('/api/admin/sign', { method: 'POST', body: JSON.stringify({ account_id: accountSelect.value }) }); const form = new FormData(); [['file', file], ['api_key', signed.apiKey], ['timestamp', signed.timestamp], ['folder', signed.folder], ['signature', signed.signature]].forEach(([key, value]) => form.append(key, value)); videoMessage.textContent = 'Uploading video to Cloudinary…'; const upload = await fetch(`https://api.cloudinary.com/v1_1/${signed.cloudName}/video/upload`, { method: 'POST', body: form }); const uploaded = await upload.json(); if (!upload.ok) throw new Error(uploaded.error?.message || 'Cloudinary upload failed'); await request('/api/admin/videos', { method: 'POST', body: JSON.stringify({ account_id: accountSelect.value, title: $('video-title').value.trim(), category: $('video-category').value.trim(), description: $('video-description').value.trim(), secure_url: uploaded.secure_url, public_id: uploaded.public_id }) }); videoForm.reset(); videoMessage.textContent = 'Video uploaded and published.'; renderVideos(); } catch (error) { videoMessage.textContent = error.message; } };
